apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-application-virtualservice
spec:
  hosts:
  - "web-application.local"
  gateways:
  - web-application-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: web-application
        port:
          number: 80
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,refused-stream
