apiVersion: v1
kind: Pod
metadata:
  name: vault-integrated-pod
spec:
  containers:
  - name: my-app-container
    image: my-app-image
    volumeMounts:
    - name: vault-secrets
      mountPath: /etc/secrets
      readOnly: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: vault-secrets
    projected:
      sources:
      - secret:
          name: my-vault-secret





