name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.5.4'
        token: ***
      
    - name: Lint Helm charts
      run: helm lint ./charts/*
          
    - name: Install Kubernetes tools (kubectl)
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
    
    - name: Deploy to Kubernetes
      run: |
